### PR TITLE
PORTF-1127 Added CACHE_ROOT_DIR envar

### PR DESCRIPTION
**Pull request by yba-siklu**
## Description
Added default CACHE_ROOT_DIR=${HOME} envar to script.

## Tests
 * Local tests only - only affects developers

## References
JIRA: PORTF-1127

### CODE REVIEW

**Comment by dima1308** [comment]
@yba-siklu what is the purpose of this change?

**Comment by yba-siklu** [comment]
> @yba-siklu what is the purpose of this change?

This change allows you to build locally and outside of the portfolio repo build system framewortk. Without it a local build wont work because the Buildroot configuration now references CACHE_ROOT_DIR for the ccache and dl cache.

**Comment by dima1308** [comment]
> > @yba-siklu what is the purpose of this change?
> 
> This change allows you to build locally and outside of the portfolio repo build system framewortk. Without it a local build wont work because the Buildroot configuration now references CACHE_ROOT_DIR for the ccache and dl cache.

maybe we need to allow the configuration of the `CACHE_ROOT_DIR` from the `portfolio/sdk_nxp/host-scripts/nxp_common_defs` file? Maybe someone prefers to put it in a different place? For example, on some PCs `HOME` dir is mounted to a small partition (for example on small SSD)

**Comment by yba-siklu** [comment]
> > > @yba-siklu what is the purpose of this change?
> > 
> > 
> > This change allows you to build locally and outside of the portfolio repo build system framewortk. Without it a local build wont work because the Buildroot configuration now references CACHE_ROOT_DIR for the ccache and dl cache.
> 
> maybe we need to allow the configuration of the `CACHE_ROOT_DIR` from the `portfolio/sdk_nxp/host-scripts/nxp_common_defs` file? Maybe someone prefers to put it in a different place? For example, on some PCs `HOME` dir is mounted to a small partition (for example on small SSD)

The purpose of the build.sh script in the buildroot-nxp-branches repo is to allow building the rootfs without any portfolio clone. This PR is not about changes in the portfolio repo.

**Comment by dima1308** [comment]
> The purpose of the build.sh script in the buildroot-nxp-branches repo is to allow building the rootfs without any portfolio clone. This PR is not about changes in the portfolio repo.

Ohh you are right, sorry.
But still, how we can avoid the situation when the `HOME` directory is too small for cache?

**Comment by yba-siklu** [comment]
> 

The developer sees that there is an error and changes the value.
Another way of handling this is to not set CACHE_ROOT_DIR in the script, but to fail the script of the CACHE_ROOT_DIR envar is not already set and provide an informative error message.

**Comment by dima1308** [comment]
> > 
> 
> The developer sees that there is an error and changes the value. Another way of handling this is to not set CACHE_ROOT_DIR in the script, but to fail the script of the CACHE_ROOT_DIR envar is not already set and provide an informative error message.

How did we solve it for the portfolio repo?
Let's discuss it on tomorrow daily

**Comment by yba-siklu** [comment]
> > > 
> > 
> > 
> > The developer sees that there is an error and changes the value. Another way of handling this is to not set CACHE_ROOT_DIR in the script, but to fail the script of the CACHE_ROOT_DIR envar is not already set and provide an informative error message.
> 
> How did we solve it for the portfolio repo? Let's discuss it on tomorrow daily

It's really not such a big issue to warrant a discussion after Daily. I'll just check to see that the envar is set.

**Review by dima1308 — APPROVED** [review]

**Pull request merged**
